Aiven-Open/tiered-storage-for-apache-kafka

s3/build.gradle, s3/src/main/resources/log4j.properties
Adding log4j configuration and slf4j-log4j12 dependency to enable logging in unit and integration tests.
=> Enable logging in unit/integration tests

docker/README.md, docker/kafka/Dockerfile, docker/s3/.gitignore, docker/s3/Makefile, docker/s3/compose.yml
Adds a Docker playground to build Kafka from source-code and add plugins for testing purposes.
No guarantee to keep it stable just yet.
The goal is to iterate faster on how users would use the plugins in their environments.
=> chore: introduce docker playground for tiered-storage

docker/s3/Makefile, docker/s3/compose.yml, s3/src/integration-test/java/io.aiven.kafka.tiered.storage.s3/S3RemoteStorageManagerTest.java, s3/src/main/java/io/aiven/kafka/tiered/storage/s3/S3RemoteStorageManager.java, s3/src/main/java/io/aiven/kafka/tiered/storage/s3/S3RemoteStorageManagerConfig.java
While enabling a testing environment (see #144), there is a need to point to localstack or minio (or any s3 compatible endpoint), but plugin currently doesn't expose this configuration.
Depends on #144
=> feat: add custom S3 endpoint URL config

build.gradle, commons/src/main/java/io/aiven/kafka/tiered/storage/commons/storage/FileDeleter.java, commons/src/main/java/io/aiven/kafka/tiered/storage/commons/storage/FileFetcher.java, commons/src/main/java/io/aiven/kafka/tiered/storage/commons/storage/FileUploader.java, commons/src/main/java/io/aiven/kafka/tiered/storage/commons/storage/ObjectStorageFactory.java, commons/src/main/java/io/aiven/kafka/tiered/storage/commons/storage/filesystem/FileSystemStorage.java, commons/src/main/java/io/aiven/kafka/tiered/storage/commons/storage/filesystem/FileSystemStorageConfig.java, commons/src/main/java/io/aiven/kafka/tiered/storage/commons/storage/filesystem/FileSystemStorageFactory.java, commons/src/test/java/io/aiven/kafka/tiered/storage/commons/storage/filesystem/FileSystemStorageConfigTest.java, commons/src/test/java/io/aiven/kafka/tiered/storage/commons/storage/filesystem/FileSystemStorageFactoryTest.java, commons/src/test/resources/log4j.properties
These interfaces are mainly supposed to be implemented with S3, GCS, and other object storage implementations, which are to be done. The file system implementation is mostly for testing.
To put this in the future context, the plugin will instantiate concrete implementations of `ObjectStorageFactory`, which will be S3, GCS, and others.
=> Add object storage interfaces and file system implementation

commons/src/main/java/io/aiven/kafka/tieredstorage/commons/ObjectKey.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/ObjectKeyTest.java
Prefix is a pre-requisite to supply an object key, moving it as a field to avoid passing it on every call
=> refactor: move object key prefix as a field

commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorage.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorageFactoryTest.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorageTest.java
When a directory is emptied on S3, the parent keys are removed until an object is found
=> fix: remove parent directories to mimic s3 behaviour

commons/src/main/java/io/aiven/kafka/tieredstorage/commons/ChunkManager.java
As Tiered Storage framework already covers the asynchronous calls to RSM, the Chunk Manager can return content as Input Stream directly.
=> fix: chunk manager: return input stream instead of future

commons/src/main/java/io/aiven/kafka/tieredstorage/commons/transform/FetchChunkEnumeration.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/transform/FetchChunkEnumerationTest.java
When fetching log segments, before processing chunks, segment position ranges need to be mapped to transformed chunks.
This PR introduces a Fetch Chunk transformation to map incoming position ranges into chunks and return chunk content.
~Depends on #187~ merged
=>  feat: add fetch chunk transform 

commons/src/main/java/io/aiven/kafka/tieredstorage/commons/Chunk.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/ChunkManager.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/BytesRange.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/FileFetcher.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorage.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/storage/BytesRangeTest.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorageFactoryTest.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorageTest.java
Range validation should be in one place instead of each storage implementation.
=> feat: add object range for fetcher

commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorage.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorageConfig.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorageFactory.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorageConfigTest.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorageFactoryTest.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorageTest.java
File system storage backend doesn't require overwrite flag as retries from RemoteStorageManager should always overwrite segments.
=> refactor: remove overwrite flag for FileSystem storage

commons/src/main/java/io/aiven/kafka/tieredstorage/commons/ChunkManager.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/UniversalRemoteStorageManager.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/FileFetcher.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/FileUploader.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/StorageBackEndException.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorage.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/transform/FetchChunkEnumeration.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorageFactoryTest.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorageTest.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/transform/FetchChunkEnumerationTest.java
Different storage back-ends will return different exceptions when reading/writing.
At the moment, storage layer has interfaces with IOException defined. This PR is proposing to have a checked exception for the whole storage layer. We can create sub-types for more specific exceptions (e.g. #208)
=> feat: add storage back-end exception

commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/KeyNotFoundException.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorage.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorageTest.java
Storage backends usually return exceptions when keys/files are not found. e.g. AmazonS3Exception 404 for S3, NoSuchFileException for FileSystem, etc. To wrap these into a common exception, this PR proposes a "KeyNotFoundException".
This exception should be catched and mapped to `RemoteResourceNotFoundException`
=> feat: add KeyNotFoundException

commons/src/main/java/io/aiven/kafka/tieredstorage/commons/UniversalRemoteStorageManager.java
When instantiated from Tiered Storage framework on the broker side, default constructor needs to be public, else fails with:
```
Caused by: java.lang.IllegalAccessException: class kafka.log.remote.RemoteLogManager$$anon$2 cannot access a member of class io.aiven.kafka.tieredstorage.commons.UniversalRemoteStorageManager with modifiers ""
```
=> fix: make URSM default constructor public

commons/src/main/java/io/aiven/kafka/tieredstorage/commons/UniversalRemoteStorageManager.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/BytesRange.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/InvalidRangeException.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorage.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/transform/FetchChunkEnumeration.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/UniversalRemoteStorageManagerTest.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/storage/BaseStorageTest.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/storage/filesystem/FileSystemStorageTest.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/transform/FetchChunkEnumerationTest.java
Couple of changes to align file-system storage with S3 and other back-ends:
- Do not throw exception when range end is larger than file size, but when range start is (introduce an "InvalidRangeException").
- Use range as inclusive start and end. Kafka TS fetch range is inclusive and S3 GET range is also inclusive.  
Depends on #215
=> refactor: align file-system storage with s3 

commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/BytesRange.java
Since BytesRange is used in log/exception messages it should have a proper `.toString` method
=> Adding toString method to BytesRange

commons/src/main/java/io/aiven/kafka/tieredstorage/commons/UniversalRemoteStorageManager.java, commons/src/main/java/io/aiven/kafka/tieredstorage/commons/UniversalRemoteStorageManagerConfig.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/SegmentCompressionCheckerTest.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/UniversalRemoteStorageManagerConfigTest.java, commons/src/test/java/io/aiven/kafka/tieredstorage/commons/UniversalRemoteStorageManagerTest.java
Use segment compression checker to validate at runtime when a segment requires compression when heuristic flag is enabled (disabled by default).
=> feat: apply compression heuristic

core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerConfig.java, core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerConfigTest.java
While we don't have the disk cache, offering `UnboundInMemoryChunkCache` (without the ability to switch it off) is not great.
=> Don't use chunk cache by default

core/src/main/java/io/aiven/kafka/tieredstorage/Chunk.java, core/src/main/java/io/aiven/kafka/tieredstorage/transform/FetchChunkEnumeration.java, core/src/test/java/io/aiven/kafka/tieredstorage/ChunkTest.java, storage/core/src/main/java/io/aiven/kafka/tieredstorage/storage/BytesRange.java, storage/core/src/test/java/io/aiven/kafka/tieredstorage/storage/BytesRangeTest.java
Fixes a bug with the range produced by a chunk with no inclusive edges.
Even though it's not affecting the results of the plugin, it pulls an additional byte on each chunk fetch.
=> fix: chunk range is not inclusive

core/src/main/java/io/aiven/kafka/tieredstorage/ChunkManager.java, core/src/test/java/io/aiven/kafka/tieredstorage/ChunkManagerTest.java
InputStream is opened but never closed when caching content.
=> fix: close storage stream on chunk manager

core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerConfig.java, core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerConfigTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerMetricsTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java
Following the convention from Kafka.
=> Rename storage.backend.class.name -> storage.backend.class

storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3MultiPartOutputStream.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3Storage.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageConfig.java, storage/s3/src/test/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageConfigTest.java, storage/s3/src/test/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageTest.java
Adds a configuration for multi-part upload. Ideally this part size should be the same as chunk size, so we gain some performance when reading[3], but this should be considered later once we have more experience with different chunk sizes.
Resolves: #233
References:
[1] Overview: https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html
[2] Multi-part upload limits: https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html
[3] https://docs.aws.amazon.com/whitepapers/latest/s3-optimizing-performance-best-practices/use-byte-range-fetches.html
> Typical sizes for byte-range requests are 8 MB or 16 MB. If objects are PUT using a multipart upload, it’s a good practice to GET them in the same part sizes (or at least aligned to part boundaries) for best performance. GET …
=> feat(storage:s3): add s3 multi-part upload part size config

build.gradle
Javadoc docs [1] :
```
-quiet
Shuts off messages so that only the warnings and errors appear to make them easier to view. It also suppresses the version string. 
```
Doclet[2]:
```
-Xdoclint all,-group: Enables all checks except group checks
```
[1]: https://docs.oracle.com/en/java/javase/17/docs/specs/man/javadoc.html
[2]: https://docs.oracle.com/en/java/javase/17/docs/specs/man/javadoc.html#additional-options-provided-by-the-standard-doclet
=> chore(build): disable javadoc lint

core/src/main/java/io/aiven/kafka/tieredstorage/chunkmanager/ChunkManagerFactoryConfig.java, core/src/main/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/DiskBasedChunkCacheConfig.java, core/src/test/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/DiskBasedChunkCacheConfigTest.java
Currently, disk-based cache is only validating if directory exist to delete it and re-create child directories.
This approach is inconsistent with how other paths are defined in the plugin, requiring the directory to exist prior to the start of the plugin. The plugin does this to avoid messing with the existing permissions around the preparation of the directory.
Applying the fixes to fail if directory doesn't exist and some additional refactoring.
=> fix(cache:disk): fail when base directory does not exist

core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/main/java/io/aiven/kafka/tieredstorage/metrics/Metrics.java, core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerMetricsTest.java
KIP-405 [1] proposes error rate metrics for read and write, but not for delete. And it's still work in progress: https://issues.apache.org/jira/browse/KAFKA-14953
Adding these metrics should give better visibility on the plugin behavior.
[1] https://cwiki.apache.org/confluence/display/KAFKA/KIP-405%3A+Kafka+Tiered+Storage#KIP405:KafkaTieredStorage-NewMetrics
=> feat(metrics): add error rate and total for upload/delete

core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/main/java/io/aiven/kafka/tieredstorage/metrics/Metrics.java, core/src/main/java/io/aiven/kafka/tieredstorage/metrics/MetricsRegistry.java, core/src/main/java/io/aiven/kafka/tieredstorage/metrics/SensorProvider.java, core/src/test/java/io/aiven/kafka/tieredstorage/NoopStorageBackend.java, core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerMetricsTest.java, storage/core/src/main/java/io/aiven/kafka/tieredstorage/storage/ObjectUploader.java, storage/core/src/testFixtures/java/io/aiven/kafka/tieredstorage/storage/BaseStorageTest.java, storage/filesystem/src/main/java/io/aiven/kafka/tieredstorage/storage/filesystem/FileSystemStorage.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3MultiPartOutputStream.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3Storage.java
Changes:
- To enable metrics to capture the number of bytes uploaded to storage backends (e.g. after transforms), `upload` is expanded to return the number of bytes uploaded.
- Metrics to measure object uploads per suffix type are added.
=> feat: measure object upload bytes

.github/workflows/create-ticket.yml
This fixes a small issue with the Jira sync script, where it's needed for HH projects so specify a component for a the ticket being created
Why this way
=> Minor fix for Jira sync

core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/main/java/io/aiven/kafka/tieredstorage/transform/BaseDetransformChunkEnumeration.java, core/src/main/java/io/aiven/kafka/tieredstorage/transform/BaseTransformChunkEnumeration.java, core/src/main/java/io/aiven/kafka/tieredstorage/transform/TransformFinisher.java, core/src/test/java/io/aiven/kafka/tieredstorage/transform/TransformsEndToEndTest.java
Changes:
- Extend transform/detransform to avoid chunking.
- Use transform/detransfom on RSM to store and serve indexes
=> feat(transform): support no chunking to encrypt indexes

core/src/integration-test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java, core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/serde/DataKeyDeserializer.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/serde/DataKeySerializer.java, core/src/main/java/io/aiven/kafka/tieredstorage/security/EncryptedDataKey.java, core/src/main/java/io/aiven/kafka/tieredstorage/security/RsaEncryptionProvider.java, core/src/main/java/io/aiven/kafka/tieredstorage/security/RsaKeyReader.java, core/src/test/java/io/aiven/kafka/tieredstorage/manifest/SegmentManifestV1SerdeTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/security/AesEncryptionProviderTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/security/EncryptedDataKeyTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/security/RsaKeyReaderTest.java
This commit is a preparation for changing how the plugin deals with encryption keys. The idea will be that there will be several RSA key encryption keys (KEK) provided in the configuration. When a data encryption key (DEK) is encrypted and written to the manifest, it comes with the ID of the KEK that encrypted it. When it's time to decrypt, the corresponding KEK is found by ID in the keyring and used for decryption.
This commit doesn't yet introduce multiple keys on the configuration level, but set's up all the necessary internal mechanics and uses a static KEK ID for now.
There will be a follow-up that actually introduces the keyring on the configuration level.
=> Identify encryption key in manifest

core/src/integration-test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java, core/src/main/java/io/aiven/kafka/tieredstorage/KeyPairPaths.java, core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerConfig.java, core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerConfigTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/RsaKeyAwareTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/manifest/SegmentManifestV1SerdeTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/security/AesEncryptionProviderTest.java
This commit makes config working on RSA keyrings instead of single key. Instead of a single pair of public and private files, it's needed to provide:
1. The list of key pairs IDs: `encryption.key.pairs`.
2. For each ID, the public and private file: `encryption.key.pairs.ID.public.key.file` and `encryption.key.pairs.ID.private.key.file`. (See e.g. how Kafka Connect configures transformations).
3. The "active" ID that will be used for encryption: `encryption.key.pair.id`.
See `RemoteStorageManagerConfigTest` for examples.
=> Provide keyring in configuration

build.gradle, core/build.gradle
This allows to avoid constant rebasing when Dependabot kicks in.
=> Distribute dependency version lines

core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/main/java/io/aiven/kafka/tieredstorage/chunkmanager/ChunkKey.java, core/src/main/java/io/aiven/kafka/tieredstorage/chunkmanager/ChunkManager.java, core/src/main/java/io/aiven/kafka/tieredstorage/chunkmanager/ChunkManagerFactory.java, core/src/main/java/io/aiven/kafka/tieredstorage/chunkmanager/DefaultChunkManager.java, core/src/main/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/ChunkCache.java, core/src/main/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/DiskBasedChunkCache.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/SegmentManifestProvider.java, core/src/main/java/io/aiven/kafka/tieredstorage/transform/FetchChunkEnumeration.java, core/src/test/java/io/aiven/kafka/tieredstorage/chunkmanager/ChunkKeyTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/chunkmanager/ChunkManagerFactoryTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/chunkmanager/DefaultChunkManagerTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/ChunkCacheMetricsTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/ChunkCacheTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/DiskBasedChunkCacheTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/manifest/SegmentManifestProviderTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/transform/FetchChunkEnumerationSourceInputStreamClosingTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/transform/FetchChunkEnumerationTest.java
To reduce coupling, and define path on RSM instead of down the chunk manager. A nice side effect is that dependencies on metadata get reduced to only RSM (where it belongs). Object Key also ends up being used only by the RSM
This changes are required by following PRs, as path to a segment can be based on the custom metadata (available on RSM). To avoid having to send another field all the way down to transformers, etc. with this change, all can be solved at the RSM level (as it's solved for indexes and manifest file.
=> refactor: Pass key path instead of log metadata + object key

core/src/main/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/ChunkCache.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/SegmentManifestProvider.java, core/src/main/java/io/aiven/kafka/tieredstorage/metrics/CaffeineStatsCounter.java, core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerMetricsTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/ChunkCacheMetricsTest.java
Cache size is not included on default Caffeine stats. Piggybacking on counter to record updates to estimated size.
Reference: https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/CaffeineStatsCounter.java
=> feat(metrics:cache): Add metric for estimated cache size

core/src/integration-test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java, core/src/main/java/io/aiven/kafka/tieredstorage/ObjectKey.java, core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/main/java/io/aiven/kafka/tieredstorage/config/RemoteStorageManagerConfig.java, core/src/main/java/io/aiven/kafka/tieredstorage/metadata/SegmentCustomMetadataBuilder.java, core/src/main/java/io/aiven/kafka/tieredstorage/metadata/SegmentCustomMetadataField.java, core/src/main/java/io/aiven/kafka/tieredstorage/metadata/SegmentCustomMetadataSerde.java, core/src/test/java/io/aiven/kafka/tieredstorage/config/RemoteStorageManagerConfigTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/metadata/SegmentCustomMetadataBuilderTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/metadata/SegmentCustomMetadataSerdeTest.java
Segment custom metadata, introduced in [KIP-917], will be adopted by plugin to collect additional processing metadata for further usage.
Initial fields:
- total bytes: Including manifest and indexes sizes to log segment size.
- object key and prefix: for further usage on read path. 
Depends on #354
To do:
[KIP-917]: https://cwiki.apache.org/confluence/display/KAFKA/KIP-917%3A+Additional+custom+metadata+for+remote+log+segment
=> feat: Adopt segment custom metadata on write

core/src/main/java/io/aiven/kafka/tieredstorage/ObjectKey.java, core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/test/java/io/aiven/kafka/tieredstorage/ObjectKeyTest.java
Follow up of #351 
Introduces usage of Custom metadata on read path.
To-do:
Depends on:
- #356
=> feat: Adopt segment custom metadata on read

core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, demo/compose-local-fs.yml, demo/compose-s3-aws.yml, demo/compose-s3-minio.yml, docker/Dockerfile, e2e/src/test/java/io/aiven/kafka/tieredstorage/e2e/SingleBrokerTest.java
Main changes:
- Update base docker image, based on https://github.com/aiven/kafka/pull/41
- Fix how to handle exception when key is not found
- Use custom metadata on demo and E2E tests
=> chore: update Kafka image with latest 3.6 changes

storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageConfig.java, storage/s3/src/test/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageConfigTest.java
It adds an option to disable the ssl cert verification, it's useful in testing scenario when it's hard/complex to install the generated root certificate into the kafka hosting machine.
=> Add option to disable SSL cert verification in the S3 client

storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageConfig.java, storage/s3/src/test/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageConfigTest.java
Adds configuration flag to disable checksum validation, and disables it by default.
We have observed that checksum validation adds ~20% more load when fetching logs. At the moment is not clear how to handle checksum issues; so this PR proposes to let Kafka handle any integrity when reading from a log. If this feature wants to be enabled, there is a new configuration to do this.
No checksum validation:
Checksum validation:
=> feat: Disable S3 checksum validation

storage/gcs/src/main/java/io/aiven/kafka/tieredstorage/storage/gcs/CredentialsBuilder.java, storage/gcs/src/main/java/io/aiven/kafka/tieredstorage/storage/gcs/GcsStorageConfig.java, storage/gcs/src/test/java/io/aiven/kafka/tieredstorage/storage/gcs/CredentialsBuilderTest.java, storage/gcs/src/test/java/io/aiven/kafka/tieredstorage/storage/gcs/GcsStorageConfigTest.java
`null` should be the default value for `gcs.credentials.default`, because otherwise certain practical combinations are impossible (e.g. just setting `gcs.credentials.json` without anything else).
Also this commit refactors how the credentials settings are validated: the validation logic is completely delegated to `CredentialsBuilder` to have it in one place.
=> Make gcs.credentials.default ternary

core/src/integration-test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java, core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/SegmentManifest.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/SegmentManifestV1.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/serde/DataKeyDeserializer.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/serde/DataKeySerializer.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/serde/EncryptionSerdeModule.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/serde/KafkaTypeSerdeModule.java, core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerMetricsTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/chunkmanager/DefaultChunkManagerTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/ChunkCacheTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/manifest/SegmentManifestProviderTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/manifest/SegmentManifestV1SerdeTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/transform/FetchChunkEnumerationSourceInputStreamClosingTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/transform/FetchChunkEnumerationTest.java
To make the segments more self-contained, this commits adds the remote log segment metadata in the manifest. However, it doesn't serialize it back (we don't need it).
Closes https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/issues/158
=> Store remote log segment metadata

core/src/integration-test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java, core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/main/java/io/aiven/kafka/tieredstorage/transform/FetchChunkEnumeration.java, core/src/main/java/io/aiven/kafka/tieredstorage/transform/KeyNotFoundRuntimeException.java
This commit makes `RemoteStorageManager` throw `RemoteResourceNotFoundException` on the fetch operation when the requested object (or the manifest object) is not found.
Closes #180
=> Correctly throw RemoteResourceNotFoundException

core/src/integration-test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java
Newly added tests were incorrect because they didn't differentiate between manifest-not-found and data-file-not-found errors.
=> Fix some RemoteStorageManagerTest

Makefile
I've replaced the perl syntax to keep only a part of the regex with a grep followed by a cat to remove the unwanted chars
=> fixed Makefile, perl isn't supported in grep for mac

storage/s3/src/integration-test/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageMetricsTest.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/MetricCollector.java
For better monitoring, latency metrics will help to understand how long are we waiting on the plugin side for a response from S3.
See commits for more details, a small refactor on the testing is included separately.
=> feat: Add S3 latency metrics

.github/workflows/main_push_and_pull_request_workflow.yml, build.gradle, e2e/build.gradle, e2e/src/test/java/io/aiven/kafka/tieredstorage/e2e/GcsSingleBrokerTest.java, storage/gcs/build.gradle
=> Add GCS e2e tests

checkstyle/suppressions.xml, core/src/integration-test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java, core/src/main/java/io/aiven/kafka/tieredstorage/ObjectKeyFactory.java, core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/SegmentIndex.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/SegmentIndexV1.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/SegmentIndexes.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/SegmentIndexesV1.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/SegmentIndexesV1Builder.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/SegmentManifest.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/SegmentManifestV1.java, core/src/test/java/io/aiven/kafka/tieredstorage/ObjectKeyFactoryTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerMetricsTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/chunkmanager/DefaultChunkManagerTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/ChunkCacheTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/manifest/SegmentIndexesV1BuilderTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/manifest/SegmentManifestProviderTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/manifest/SegmentManifestV1SerdeTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/transform/FetchChunkEnumerationSourceInputStreamClosingTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/transform/FetchChunkEnumerationTest.java, e2e/src/test/java/io/aiven/kafka/tieredstorage/e2e/SingleBrokerTest.java
By having indexes together, the number of objects stored in remote tier got reduced from 4 or 5 to 1. Range fetch used to get specific indexes.
=> feat: concat indexes in the same object

core/src/main/java/io/aiven/kafka/tieredstorage/metadata/SegmentCustomMetadataBuilder.java
Complete the suggestion proposed here [1]
[1]: https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/pull/351#discussion_r1295888748
=> fix: use index instead of ordinal for metadata fields

docker/kafka-jmx-exporter.yml, storage/gcs/src/main/java/io/aiven/kafka/tieredstorage/storage/gcs/GcsStorage.java, storage/gcs/src/main/java/io/aiven/kafka/tieredstorage/storage/gcs/MetricCollector.java, storage/gcs/src/test/java/io/aiven/kafka/tieredstorage/storage/gcs/MetricCollectorRegexTest.java
GCS bucket names can contain hyphens, underscores, dots, etc: https://cloud.google.com/storage/docs/buckets
Fixing the regex to match URLs, and a couple of minor related refactoring. See commits for details.
=> fix: capture GCS metrics when bucket contains hyphens

docker/Dockerfile, e2e/src/test/java/io/aiven/kafka/tieredstorage/e2e/SingleBrokerTest.java
The disk-based is more complex and also more realistic to be used in production.
=> Use disk-based cache in E2E tests

core/src/integration-test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java, core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java
Index size can potentially be zero or too large for transformation to work.
=> feat: validate index size when transforming

core/src/integration-test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java, core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java
This commit addresses the fact that the fetching stream can be interrupted by the broker. In this case, we return an empty stream to prevent useless logging of `InterruptedException` and `ClosedByInterruptException`.
=> Handle interruptions during fetching log segment

core/src/integration-test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java, core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/SegmentIndexesV1Builder.java, core/src/test/java/io/aiven/kafka/tieredstorage/manifest/SegmentIndexesV1BuilderTest.java, docker/Dockerfile
By ignoring empty indexes--that is a valid case when segment sizes are too small; even if not recommended--the requirement to have at least 4 indexes when uploaded was not met.
This fix improves the logging to show what indexes are included therefore know which one is missing; and includes a fix to add empty indexes to the builder.
See commits for more details. It includes moving some RSM tests from IT to unit tests.
=>  fix: add empty indexes to builder 

checkstyle/suppressions.xml, core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/main/java/io/aiven/kafka/tieredstorage/config/CacheConfig.java, core/src/main/java/io/aiven/kafka/tieredstorage/config/RemoteStorageManagerConfig.java, core/src/main/java/io/aiven/kafka/tieredstorage/fetch/index/MemorySegmentIndexesCache.java, core/src/main/java/io/aiven/kafka/tieredstorage/fetch/index/SegmentIndexKey.java, core/src/main/java/io/aiven/kafka/tieredstorage/fetch/index/SegmentIndexesCache.java, core/src/test/java/io/aiven/kafka/tieredstorage/config/CacheConfigTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/fetch/SegmentIndexKeyTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/fetch/index/MemorySegmentIndexesCacheTest.java, demo/Makefile
Indexes are currently cached on broker-side but with a synchronous cache that is not able to source value when interrupted.
This new cache will fetch index asynchronously, and retries would have chances to find the value sourced already.
=>  feat: add async cache for segment indexes 

core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/main/java/io/aiven/kafka/tieredstorage/fetch/FetchChunkEnumeration.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/index/AbstractChunkIndex.java, core/src/test/java/io/aiven/kafka/tieredstorage/ChunkTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/manifest/SegmentIndexesV1BuilderTest.java, storage/azure/src/main/java/io/aiven/kafka/tieredstorage/storage/azure/AzureBlobStorage.java, storage/core/src/main/java/io/aiven/kafka/tieredstorage/storage/BytesRange.java, storage/core/src/test/java/io/aiven/kafka/tieredstorage/storage/BytesRangeTest.java, storage/filesystem/src/main/java/io/aiven/kafka/tieredstorage/storage/filesystem/FileSystemStorage.java, storage/gcs/src/main/java/io/aiven/kafka/tieredstorage/storage/gcs/GcsStorage.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3Storage.java
Given that indexes could be empty, inclusive ranges should be able to represent the case where size is zero. 
To do this, `to=-1` is proposed to represent ranges that are empty.
Historically, ranges were designed only for segments where empty files were not possible. As recently empty indexes became a possibility when small segment files are created, then the initial design of BytesRange became an issue as it's designed as inclusive-inclusive.
=> feat: extend BytesRange to support empty ranges

docker/Dockerfile
Use latest 3.6.1 + some bug fixes, see https://github.com/apache/kafka/compare/3.6...aiven:kafka:3.6.1-2024-02-06
=> chore: bump base docker image for testing/demo

core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerMetricsTest.java, storage/core/src/main/java/io/aiven/kafka/tieredstorage/storage/ObjectDeleter.java, storage/core/src/testFixtures/java/io/aiven/kafka/tieredstorage/storage/BaseStorageTest.java, storage/s3/src/integration-test/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageMetricsTest.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/MetricCollector.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3Storage.java
Some Storage back-ends have the ability to delete multiple objects at once. To allow them to use this optimization, the ObjectDeleter interface is extended to allow passing multiple object keys at once.
Fix #319
PS. Was considering GCS initially, but given that FakeGcs server doesn't seem to properly handle the `delete(List of BlobId)` -- at least metrics where not processed -- and implementation seems to be syntactic sugar; then I decided to postpone it and only focused on S3.
=> feat: extend object deleter to delete multiple keys at once when supported by back-end

storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3ClientBuilder.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3Storage.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageConfig.java, storage/s3/src/test/java/io/aiven/kafka/tieredstorage/storage/s3/S3ClientBuilderTest.java, storage/s3/src/test/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageConfigTest.java
Creating the client shouldn't really be done in the config class. This commit extracts it into a separate class.
=> Move S3Client creation from S3StorageConfig

storage/s3/src/integration-test/java/io/aiven/kafka/tieredstorage/storage/s3/S3ErrorMetricsTest.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3Storage.java
There's no reason in passing raw HTTP/IO and other similar exceptions upstream.
=> Wrap more S3 errors in StorageBackendException

storage/s3/build.gradle
STS is a very popular credentials provider. It's good to have it in the S3 storage distribution.
Resolves #511
=> Include AWS STS in S3 storage distro

core/src/integration-test/java/io/aiven/kafka/tieredstorage/AllOpenedFileInputStreamsAreClosedChecker.java, core/src/integration-test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java, core/src/main/java/io/aiven/kafka/tieredstorage/ClosableInputStreamHolder.java, core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/test/java/io/aiven/kafka/tieredstorage/ClosableInputStreamHolderTest.java
Closes #513
It's easier to review `RemoteStorageManager.java` if you hide white spaces in Github or your IDE.
=> Close file InputStreams when copying segments

.github/workflows/create_release.yml
Tested on a fork, looks like this: https://github.com/jeqo/tiered-storage-for-apache-kafka/releases/tag/v0.0.1
=> chore(release): add libraries to release page

storage/azure/src/integration-test/java/io/aiven/kafka/tieredstorage/storage/azure/AzureBlobStorageSocks5Test.java
Seems the current possible messages need to be extended when the integration tests for proxy is running on a mac. The exceptions could be slightly different.
Some similarity with other stacks trying to handle similar errors: [1]
[1]: https://github.com/Shopify/semian/blob/ebe30df94cebc74d28e020206d6a2fa2019aeed7/lib/semian/redis.rb#L166
=> fix: extend possible root causes message

docker/Dockerfile, e2e/src/test/java/io/aiven/kafka/tieredstorage/e2e/SingleBrokerTest.java, e2e/src/test/java/io/aiven/kafka/tieredstorage/e2e/internal/RemoteLogMetadataTracker.java
Kafka 3.7 have changed how local retention affects active segment: from now on, if local retention time is passed, then a new (empty) active segment is rollout.
This changes how the end-to-end tests validated deletion by retention.
Apart from this change, the PR includes some e2e test improvements: adding docs to make the sequence of steps on the end-to-end test easier to follow; some reorganization and renaming with the same purpose. See the commits for more detail.
=> chore: bump E2E tests for Kafka 3.7

README.md, build.gradle, core/build.gradle, core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/main/java/io/aiven/kafka/tieredstorage/config/RemoteStorageManagerConfig.java, core/src/main/java/io/aiven/kafka/tieredstorage/transform/RateLimitedInputStream.java, core/src/main/java/io/aiven/kafka/tieredstorage/transform/TransformFinisher.java, core/src/test/java/io/aiven/kafka/tieredstorage/config/RemoteStorageManagerConfigTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/transform/RateLimitedInputStreamTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/transform/TransformFinisherTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/transform/TransformsEndToEndTest.java, e2e/src/test/java/io/aiven/kafka/tieredstorage/e2e/SingleBrokerTest.java
When uploading segments, there is no limitation on how many resources to use (CPU, Network, Disk bandwidth). Given that many threads are started on the same broker and upload segments concurrently, this could affect the broker performance.
This PR aims to provide a limitation for the input stream offered to storage backends to limit how many bytes can be read per second. To do that, Bucket4j rate limiting library is used to provide a bucket with the configured upper bound per RSM (i.e. per broker).
Inspired by #521
=> feat: add rate limited input stream for uploads

README.md
1. typo in ReadMe
2. broken link for `ChunkSizesBinaryCodec` javadoc.
=> docs: fix typo and broken link in ReadMe

core/build.gradle, storage/gcs/build.gradle
In the released core zip, we included 
1. caffeine-3.1.8.jar
2. checker-qual-3.37.0.jar
3. error_prone_annotations-2.21.1.jar
From this discussion in Caffeine project: https://github.com/ben-manes/caffeine/issues/300#issuecomment-507292996 . The author of Caffeine project:
> checker-qual And errorprone are annotations which Java doesn’t require at runtime unless you reflectively load them when inspecting the methods. Unfortunately other languages will not classload without them, making them required. You can exclude safely in Java.
Since we only use JAVA and it doesn't cause any errors while compiling after excluding them, I think we should remove them from the distribution zip.
=> fix: exclude unnecessary modules in Caffeine

storage/s3/src/integration-test/java/io/aiven/kafka/tieredstorage/storage/s3/S3ErrorMetricsTest.java
Fixing the s3 integration tests.
The s3 integraion tests are using `s3.bucket.name` set to "test-bucket" and `s3.endpoint.url` set to "http://localhost:...".
Then, the client uses the hostname `test-bucket.localhost`, which causes those tests to fail with UnknownHostException.
```
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: test-bucket.localhost
at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47)
at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:223)
at …
```
=> Avoid hostname errors from s3 integration tests

storage/s3/src/integration-test/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageTest.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/MetricCollector.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3MultiPartOutputStream.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3Storage.java, storage/s3/src/test/java/io/aiven/kafka/tieredstorage/storage/s3/S3MultiPartOutputStreamTest.java
Use only ByteRange slices to pass bytes to S3 client operations and remove array copying.
Doing some benchmarks on the current implementation, the Arrays.copyOfRange dominates the memory allocation:
By switching to the ByteBuffer approach, this copying is removed:
=> fix(s3): reducing array copying on S3 output stream

core/src/test/java/io/aiven/kafka/tieredstorage/manifest/SegmentIndexV1Test.java, core/src/test/java/io/aiven/kafka/tieredstorage/manifest/SegmentIndexesV1Test.java, core/src/test/java/io/aiven/kafka/tieredstorage/manifest/SegmentManifestV1Test.java
Fix #417 
Nothing else to add other than what is written in the title.
=> Add equals() and hashCode() tests for manifests classes

docker/Dockerfile
Update docker base image to 3.8.
=>  chore: upgrading docker base image to kafka 3.8

core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java
Given that there are at least 3 objects uploaded per segment, and it could fail at any stage, the plugin should guard that the chances for orphan objects is minimal.
=> feat: remove orphan objects if copy fails at any point

.gitignore, checkstyle/suppressions.xml, core/src/main/java/io/aiven/kafka/tieredstorage/config/CacheConfig.java, core/src/main/java/io/aiven/kafka/tieredstorage/fetch/cache/ChunkCache.java, core/src/main/java/io/aiven/kafka/tieredstorage/fetch/index/MemorySegmentIndexesCache.java, core/src/main/java/io/aiven/kafka/tieredstorage/fetch/manifest/MemorySegmentManifestCache.java, core/src/test/java/io/aiven/kafka/tieredstorage/config/CacheConfigTest.java
Currently the ForkJoinPools used by the fetch caches (chunk, indexes, and manifest) are defined by default. Also, the fetching is timeout by default to 10secs.
This PR aims to introduce thread-pool size and timeout configurations to the cache config to each fetch cache, to allow tuning.
=> feat: additional configs for caches

core/src/main/java/io/aiven/kafka/tieredstorage/transform/BaseDetransformChunkEnumeration.java, core/src/main/java/io/aiven/kafka/tieredstorage/transform/DetransformFinisher.java, core/src/test/java/io/aiven/kafka/tieredstorage/transform/DetransformFinisherTest.java
When there is no detransform action defined (decompress, decrypt) avoid going through the pipeline which requires allocating byte[] per chunk. Instead pass the source inputstream that already contains the chunks requested.
=> refactor: avoid allocation on fetch detransform

core/src/integration-test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java, core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java, core/src/main/java/io/aiven/kafka/tieredstorage/manifest/SegmentEncryptionMetadataV1.java, core/src/main/java/io/aiven/kafka/tieredstorage/transform/BaseDetransformChunkEnumeration.java, core/src/main/java/io/aiven/kafka/tieredstorage/transform/BaseTransformChunkEnumeration.java, core/src/main/java/io/aiven/kafka/tieredstorage/transform/TransformFinisher.java, core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/transform/TransformFinisherTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/transform/TransformsEndToEndTest.java
Pass directly the file input stream to the storage layer instead of calculating chunks on the fly. Optimizes for the default configuration (no encryption/compression), and prepares for further passing the path to the storage layer if uploading directly from file is preferred.
It contains a couple of meaningful refactoring to clean up RSM logic and simplify chunking. See commits for further details.
=> feat: bypass chunking when no transformation is requested

core/src/main/java/io/aiven/kafka/tieredstorage/config/CacheConfig.java, core/src/main/java/io/aiven/kafka/tieredstorage/config/ChunkCacheConfig.java, core/src/main/java/io/aiven/kafka/tieredstorage/config/ChunkManagerFactoryConfig.java, core/src/main/java/io/aiven/kafka/tieredstorage/config/DiskChunkCacheConfig.java, core/src/main/java/io/aiven/kafka/tieredstorage/fetch/ChunkManagerFactory.java, core/src/main/java/io/aiven/kafka/tieredstorage/fetch/cache/MemoryChunkCache.java, core/src/main/java/io/aiven/kafka/tieredstorage/fetch/index/MemorySegmentIndexesCache.java, core/src/main/java/io/aiven/kafka/tieredstorage/fetch/manifest/MemorySegmentManifestCache.java, core/src/test/java/io/aiven/kafka/tieredstorage/config/CacheConfigTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/config/ChunkCacheConfigTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/config/ChunkManagerFactoryConfigTest.java
This is needed for documentation purposes (#601), while also improving the cache config builder.
=> refactor: expose configDef() for all cache config sets

.github/workflows/git.yml, Makefile, commons/src/main/java/io/aiven/kafka/tieredstorage/config/validators/NonEmptyPassword.java, commons/src/main/java/io/aiven/kafka/tieredstorage/config/validators/Null.java, commons/src/main/java/io/aiven/kafka/tieredstorage/config/validators/Subclass.java, commons/src/main/java/io/aiven/kafka/tieredstorage/config/validators/ValidUrl.java, config.rst, core/src/main/java/io/aiven/kafka/tieredstorage/config/RemoteStorageManagerConfig.java, docs/build.gradle, docs/src/main/java/io/aiven/kafka/tieredstorage/misc/ConfigDocs.java, settings.gradle, storage/azure/src/main/java/io/aiven/kafka/tieredstorage/storage/azure/AzureBlobStorageConfig.java, storage/filesystem/src/main/java/io/aiven/kafka/tieredstorage/storage/filesystem/FileSystemStorageConfig.java, storage/gcs/src/main/java/io/aiven/kafka/tieredstorage/storage/gcs/GcsStorageConfig.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageConfig.java
Improves config descriptions and adds doc module.
See commits for more details.
Adding a git check to ensure docs are updated when source changes. Validation: https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/actions/runs/11164414848/job/31033700687?pr=601
=> chore: add config docs generation

core/src/main/java/io/aiven/kafka/tieredstorage/fetch/cache/ChunkCache.java, core/src/main/java/io/aiven/kafka/tieredstorage/fetch/index/MemorySegmentIndexesCache.java, core/src/main/java/io/aiven/kafka/tieredstorage/fetch/manifest/MemorySegmentManifestCache.java, core/src/main/java/io/aiven/kafka/tieredstorage/metrics/CaffeineMetricsRegistry.java, core/src/main/java/io/aiven/kafka/tieredstorage/metrics/CaffeineStatsCounter.java, core/src/main/java/io/aiven/kafka/tieredstorage/metrics/Metrics.java, core/src/main/java/io/aiven/kafka/tieredstorage/metrics/MetricsRegistry.java, core/src/main/java/io/aiven/kafka/tieredstorage/metrics/ThreadPoolMonitor.java, core/src/main/java/io/aiven/kafka/tieredstorage/metrics/ThreadPoolMonitorMetricsRegistry.java
Add a metric registry for Caching and Thread Pool metrics, document metrics, and expose metric name templates to be used on documentation generation.
=> refactor: expose core metric names for doc generation 

storage/azure/src/main/java/io/aiven/kafka/tieredstorage/storage/azure/MetricCollector.java, storage/azure/src/main/java/io/aiven/kafka/tieredstorage/storage/azure/MetricRegistry.java, storage/gcs/src/main/java/io/aiven/kafka/tieredstorage/storage/gcs/MetricCollector.java, storage/gcs/src/main/java/io/aiven/kafka/tieredstorage/storage/gcs/MetricRegistry.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/MetricCollector.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/MetricRegistry.java
Add a metric registry for Azure, GCS, S3 metrics, document metrics, and expose metric name templates to be used on documentation generation.
=> refactor: expose storage backends metric names for doc generation

docs/configs.rst
I was digging into the project and was trying to figure out how the chunks are set in GCS. After reading this project's code and the GCS SDK's code - I understood how the SDK defaults to resumable uploads. I figured it's useful to explicitly mention how we default to GCS's default when we set it to null and link to the source - for future compatibility, e.g if/when GCS changes their default
=> MINOR: Explicitly document how the minimum GCS resumable upload chunksize is set

.github/workflows/git.yml, Makefile, checkstyle/suppressions.xml, docs/build.gradle, docs/configs.rst, docs/metrics.rst, docs/src/main/java/io/aiven/kafka/tieredstorage/misc/ConfigsDocs.java, docs/src/main/java/io/aiven/kafka/tieredstorage/misc/MetricsDocs.java, storage/gcs/src/main/java/io/aiven/kafka/tieredstorage/storage/gcs/GcsStorageConfig.java
Configuration and metrics are documented on the code, and RST files are generated from there. 
This fix aligns the GCSStorageConfig with the updated RST (in #615), and clarifies the relation.
See commits for details.
=> chore: clarify docs generation

demo/README.md, demo/compose-azure-blob-azurite.yml, demo/compose-gcs-fake-gcs-server.yml, demo/compose-local-fs.yml, demo/compose-s3-aws.yml, demo/compose-s3-minio.yml, docker/Dockerfile, docker/kafka-jmx-exporter.yml
Update and fix docker-related configs. See commit for more details.
=> chore(docker): bump docker image and dependencies

core/src/main/java/io/aiven/kafka/tieredstorage/config/CacheConfig.java, core/src/main/java/io/aiven/kafka/tieredstorage/fetch/manifest/MemorySegmentManifestCache.java, core/src/test/java/io/aiven/kafka/tieredstorage/config/CacheConfigTest.java, docs/configs.rst
The doc suggested that cache size is measured in bytes however it's measured in units.
=> docs: fix segment manifest cache size doc

docs/build.gradle
In Intellij, when loading the project and running `clean` phase, the docs are getting cleaned up.
Adding a fix to avoid this.
=> fix(build): avoid removing docs on clean

docs/configs.rst, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3MultiPartOutputStream.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3Storage.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageConfig.java, storage/s3/src/test/java/io/aiven/kafka/tieredstorage/storage/s3/S3MultiPartOutputStreamTest.java, storage/s3/src/test/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageConfigTest.java
Hi Team:
Thanks for provide so cool tool to support kafka tiered-storage. 
Refer to the document: 
https://aws.amazon.com/s3/storage-classes/?nc1=h_ls
We can know the storage class feature is the core important feature for s3 which involve the cost and performance.
We had adopt tiered storage implement in our Kafka for cost saving goal. thus, we find that all of the Kafka data uploaded by the standard default storage class. So try to create this PR to support the setting for storage class. So that we can get more cost saving.
Thanks in advanced.  WDYT?
FYI:
=> Support setting storage class for S3 to reduce cost

core/src/main/java/io/aiven/kafka/tieredstorage/fetch/cache/DiskChunkCache.java
Sometime `DiskChunkCache.removalListener()` fails with `NoSuchFileException`, it's not yet understood why this happens (could be some race condition), but it's good practice fror a delete operation to not fail if the file to remove is not present. This PR is a slightly less invasive version of https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/pull/569 (less code changed), since the previous PR raised some concerns.
Tested this locally by adding the annotation @RepeatedTest(10000) on `DiskChunkCacheMetricsTest.metrics()`, without my PR sometimes it fails randomly.
=> fix: remove listener should not cause exceptions when the file is not present

.gitignore, Makefile, benchmarks/README.md, benchmarks/build.gradle, benchmarks/jmh.sh, benchmarks/src/main/java/io/aiven/kafka/tieredstorage/benchs/AesKeyAware.java, benchmarks/src/main/java/io/aiven/kafka/tieredstorage/benchs/transform/DetransformBench.java, benchmarks/src/main/java/io/aiven/kafka/tieredstorage/benchs/transform/TransformBench.java, benchmarks/src/main/resources/log4j.properties, checkstyle/suppressions.xml, settings.gradle
Include a new module to host JMH benchmarks from TS plugin components and benchmarks for transform/detransform.
Follow a similar setup as the benchmarks on apache/kafka to simplify customizing arguments.
=> chore: add jmh benchmarks module

build.gradle, storage/core/build.gradle
This change includes:
- Add signing plugin
- Add sonatype repo
- Include maven pom properties to be published
- Task to publish specific modules
- Allowed test-fixture jars to be included in the package (requested here: https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/pull/583#issuecomment-2694522529). Instead filter-out test-fixtures and sources from distributions
I have tested the publishing to sonatype with snapshots and it's looking good: https://oss.sonatype.org/service/local/repositories/snapshots/content/io/aiven/tiered-storage-for-apache-kafka-storage-core/0.0.1-SNAPSHOT/tiered-storage-for-apache-kafka-storage-core-0.0.1-20250306.172800-8-test-fixtures.jar
=> chore(build): publish to sonatype

storage/gcs/src/main/java/io/aiven/kafka/tieredstorage/storage/gcs/GcsStorage.java
There is a claim on the GcsStorage about get() call having 2 requests executed (and charged for).
Adding the source to clarify further discussions.
Answers question: https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/issues/616#issuecomment-2439719261
=> docs: add source for gcs >1 op per SDK call

checkstyle/suppressions.xml, storage/core/src/testFixtures/java/io/aiven/kafka/tieredstorage/storage/BaseStorageTest.java, storage/s3/src/integration-test/java/io/aiven/kafka/tieredstorage/storage/s3/S3ErrorMetricsTest.java, storage/s3/src/integration-test/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageMetricsTest.java, storage/s3/src/integration-test/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageTest.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/ByteBufferMarkableInputStream.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3Storage.java, storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3UploadOutputStream.java, storage/s3/src/test/java/io/aiven/kafka/tieredstorage/storage/s3/ByteBufferMarkableInputStreamTest.java, storage/s3/src/test/java/io/aiven/kafka/tieredstorage/storage/s3/S3UploadOutputStreamTest.java
Kafka have three type of the files which need to upload as followed:
Most of file with the type("rsm-manifest" and "indexes") don't have > 5M size (Which is the default upload part size). So for these type of the files and some small size log segement. There is no need to upload by multipart. 
This PR is to improve the upload logic to reduce the requests and related cost also (request is typical cost item).
I add some logs as test code to classify the issue: 
It send **3** requests for one file with size: 901.
[2025-03-18 06:28:38,160] INFO **CreateMultipartUploadRequest**: test_topic/27/00000000009398949865-GyuaUKJ3QEWC-ILUqyUt9A.rsm-manifest  cost: 16ms 
[2025-03-18 06:28:38,180] INFO **UploadPartRequest**: test_topic/27/00000000009398949865-GyuaUKJ3QEWC-ILUqyUt9A.rsm-manifest with …
=> Improve the s3 upload logic to reduce requests and fix retry fail issue

gradle.properties
Used the wrong commit type, and version commits got squashed.
Reverts Aiven-Open/tiered-storage-for-apache-kafka#689
=> Revert "Release version 1.0.0"

core/src/test/java/io/aiven/kafka/tieredstorage/fetch/cache/ChunkCacheMetricsTest.java, core/src/test/java/io/aiven/kafka/tieredstorage/fetch/manifest/MemorySegmentManifestCacheMetricsTest.java
- Fixes flaky metrics tests. 
Resolves: #690
Why this way
Next logs indicates the cause of issue:
- added verbose logging in multiple places + thread producing logs
- simulated delay in metrics publish to make case reproducible
Method modified to reproduce: **io.aiven.kafka.tieredstorage.metrics.CaffeineStatsCounter#recordLoadSuccess**
```
@Override
public void recordLoadSuccess(final long loadTime) {
cacheLoadSuccessCount.increment();
log.info("Incremented load success count: {}", cacheLoadSuccessCount.sum());
try {
log.info("Simulating delay for time recording.");
Thread.sleep(1000);
} catch (InterruptedException e) {
throw new RuntimeException(e);
}
log.info("Before recording success time total");
cacheLoadSuccessTimeTotal.add(loadTime);
log.info("After …
```
=> fix(build): Flaky ChunkCacheMetricsTest

.github/workflows/codeql-analysis.yml, .github/workflows/main_push_and_pull_request_workflow.yml
As we're starting depending on some broker internals which are built for min Java 17, remove Java 11 from the versions.
=> Remove Java 11 from pipeline

build.gradle
Since the dependency is already there, enabling it in pitest plugin breaks some Intellij features.
Why this way
=> Excluding JUnitPlatformLauncher from pitest configuration

storage/s3/build.gradle
Apache Iceberg 1.10.0 has hard dependency on KMS.
Why this way
=> Adding AWS KMS dependency.

demo/iceberg/README.md
About this change - Tidying. 
1. README had a MD link, there was an extra space that broke the formatting and showed the raw link.
2. Unable to login to Nimtable without the creds, I guessed the default and have included that in the doc.
3. Added SQL snippet for those less familiar with Nimtable to get started quicker.
=> More docs for iceberg demo
