- build.gradle
- commons/build.gradle
- commons/src/main/java/io/aiven/kafka/tiered/storage/commons/security/EncryptionKeyProvider.java
- s3/build.gradle
See individual commit messages
> Some fixe proposals

- build.gradle
- checkstyle/suppressions.xml
- s3/src/integration-test/java/io.aiven.kafka.tiered.storage.s3/S3RemoteStorageManagerTest.java
- s3/src/main/java/io/aiven/kafka/tiered/storage/s3/NonEmptyPassword.java
- s3/src/main/java/io/aiven/kafka/tiered/storage/s3/S3ClientWrapper.java
- s3/src/main/java/io/aiven/kafka/tiered/storage/s3/S3EncryptionKeyProvider.java
- s3/src/main/java/io/aiven/kafka/tiered/storage/s3/S3RemoteStorageManager.java
- s3/src/main/java/io/aiven/kafka/tiered/storage/s3/S3RemoteStorageManagerConfig.java
- s3/src/test/java/io/aiven/kafka/tiered/storage/s3/S3RemoteStorageManagerConfigTest.java
See commit messages for details
> Various fixes

- .github/workflows/pull_request_workflow.yml
> Removing branch filtering for PR pipelines

- build.gradle
> Upgrading JaCoCo version

- .github/workflows/main_push_workflow.yml
- .github/workflows/pull_request_workflow.yml
> Adding Java 17 to CI pipeline

- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/TestObjectStorageFactory.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/UniversalRemoteStorageManagerConfigTest.java
To clarify how Config will pass from framework to plugin
> test: add Config to test object storage

- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/UniversalRemoteStorageManagerConfig.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/UniversalRemoteStorageManagerConfigTest.java
> Adding path prefix to UniversalRemoteStorageManagerConfig

- s3/src/main/java/io/aiven/kafka/tiered/storage/s3/S3EncryptionKeyProvider.java
> fix: s3: import order

- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/security/AesEncryptionProvider.java
- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/security/RsaEncryptionProvider.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/UniversalRemoteStorageManagerTest.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/io/CryptoIOProviderTest.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/manifest/SegmentManifestV1SerdeTest.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/security/EncryptionProviderTest.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/security/RsaKeysReaderTest.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/security/metadata/EncryptedRepositoryMetadataTest.java
- s3/src/main/java/io/aiven/kafka/tiered/storage/s3/S3EncryptionKeyProvider.java
Changes:
- Moves RSA Path into InputStream mapping into one place
- Creates an AES Encryption Provider out of an RSA Encryption provider.
> refactor: aes and rsa keys initialization

- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/InvalidRecordBatchException.java
- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/SegmentCompressionChecker.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/SegmentCompressionCheckerTest.java
Validates if compression is required on a segment or not.
Fix #173
> feat: segment compression checker

- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/Chunk.java
- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/ChunkKey.java
- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/manifest/SegmentEncryptionMetadataV1.java
- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/manifest/index/FixedSizeChunkIndex.java
- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/manifest/index/VariableSizeChunkIndex.java
> Add and fix some toString

- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/manifest/index/FixedSizeChunkIndex.java
- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/manifest/index/VariableSizeChunkIndex.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/manifest/index/ChunkIndexSerializationTest.java
> Require fields in JSON deserialization of chunk indices

- checkstyle/suppressions.xml
- commons/build.gradle
- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/UniversalRemoteStorageManager.java
- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/UniversalRemoteStorageManagerConfig.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/UniversalRemoteStorageManagerTest.java
Adding RemoteStorageManager implementation that supposed to be used as a single entry point all possible future remote storage implementations.
> UniversalRemoteStorageManager implementation

- checkstyle/suppressions.xml
- commons/build.gradle
- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/storage/s3/S3StorageConfig.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/storage/s3/S3StorageConfigTest.java
> feat: add S3 config class

- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/UniversalRemoteStorageManager.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/UniversalRemoteStorageManagerMetricsTest.java
This commit adds only one metric--segment copies per second--but it lays the foundation for further adding more metrics.
> Add metrics

- settings.gradle
> Remove s3 subproject from Gradle

- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/security/AesEncryptionProvider.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/security/AesEncryptionProviderTest.java
We're going to replace Bouncy Castle with the JDK crypto library, which cannot generate 512 bit AES keys. We don't in fact need 512 bits, it was just used to simultaneously generate a key and an AAD. Effectively, splitting in two calls in this commit.
> Refactor AES key generation

- checkstyle/suppressions.xml
- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/RemoteStorageManager.java
- commons/src/main/java/io/aiven/kafka/tieredstorage/commons/RemoteStorageManagerConfig.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/RemoteStorageManagerConfigTest.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/RemoteStorageManagerMetricsTest.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/commons/RemoteStorageManagerTest.java
> refactor: renaming UniversalRSM to RSM

- .github/workflows/main_push_workflow.yml
- .github/workflows/pull_request_workflow.yml
It's good to check this final step works too.
> Run releaseTarGz on workflows

- core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java
- core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerMetricsTest.java
- `segment-copy-time-avg`
- `segment-copy-time-max`
- `segment-fetch-rate`
> Add some metrics

- core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java
- core/src/main/java/io/aiven/kafka/tieredstorage/metrics/Metrics.java
To control the growth of `RemoteStorageManager`.
> Encapsulate metrics code into Metrics class

- checkstyle/suppressions.xml
Updates references to class names on suppressions.
> chore(build): update checkstyle suppresssions

- build.gradle
> Adding PITest

- storage/s3/src/integration-test/resources/log4j.properties
> chore(storage:s3): add log4j config to integration tests

- core/src/main/java/io/aiven/kafka/tieredstorage/transform/FetchChunkEnumeration.java
- core/src/test/java/io/aiven/kafka/tieredstorage/transform/FetchChunkEnumerationSourceInputStreamClosingTest.java
> Getting rid of unnecessary chunk fetching

- README.md
Document multipart upload and how to deal with incomplete uploads.
> docs(storage:s3): add note for aborting incomplete mpu

- demo/Makefile
- demo/README.md
Include more options to create topics and smaller fixes.
> feat(demo): add more options

- demo/compose-local-fs.yml
- demo/compose-s3-aws.yml
- demo/compose-s3-minio.yml
> feat(demo): Increase logger level for TS classes

- core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java
- core/src/main/java/io/aiven/kafka/tieredstorage/metrics/Metrics.java
- core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerMetricsTest.java
Changes:
- Add segment delete time metric
- Add total metric to segment fetch requests
- Add fetch bytes metric
> feat(metrics): additional metrics

- checkstyle/suppressions.xml
- core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java
- core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerConfig.java
- core/src/main/java/io/aiven/kafka/tieredstorage/metrics/Metrics.java
- core/src/main/java/io/aiven/kafka/tieredstorage/metrics/MetricsRegistry.java
- core/src/main/java/io/aiven/kafka/tieredstorage/metrics/SensorProvider.java
- core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerMetricsTest.java
Changes:
- Add topic and partition label to existing metrics.
- Refactor the metrics module to provide metric sensor if already exists.
> feat(metrics): tag RSM metrics by topic and partition

- README.md
> Document local cache

- core/src/main/java/io/aiven/kafka/tieredstorage/RemoteStorageManager.java
- core/src/main/java/io/aiven/kafka/tieredstorage/config/KeyPairPaths.java
- core/src/main/java/io/aiven/kafka/tieredstorage/config/RemoteStorageManagerConfig.java
- core/src/test/java/io/aiven/kafka/tieredstorage/config/NoopStorageBackend.java
- core/src/test/java/io/aiven/kafka/tieredstorage/config/RemoteStorageManagerConfigTest.java
> Create config package

- build.gradle
Between API and log4j backend for tests.
> Use single slf4j version

- build.gradle
See https://github.com/Aiven-Open/opensearch-connector-for-apache-kafka/pull/219#issuecomment-1651850483
> Revert slf4j back to 1.7.36

- core/src/main/java/io/aiven/kafka/tieredstorage/metrics/CaffeineStatsCounter.java
- core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerMetricsTest.java
CaffeineStatsCounter refactoring that removes unnecessary calls to Sensor.record to improve metrics performance.
> CaffeineStatsCounter performance improvements

- core/src/integration-test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java
- core/src/main/java/io/aiven/kafka/tieredstorage/chunkmanager/ChunkManagerFactoryConfig.java
- core/src/main/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/ChunkCache.java
- core/src/main/java/io/aiven/kafka/tieredstorage/metrics/CaffeineStatsCounter.java
- core/src/test/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/ChunkCacheMetricsTest.java
- core/src/test/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/DiskBasedChunkCacheTest.java
Refactors Disk-based cache to report metrics, and includes Caffeine instrumentation to chunk-cache.
Depends on #322
> feat(metrics): add cache metrics to chunk cache

- demo/Makefile
- demo/README.md
Changes:
- Add replication factor variable
- Disable time-based retention when size-based topics are created.
> fix(demo): improve Makefile commands

- commons/build.gradle
- commons/src/main/java/io/aiven/kafka/tieredstorage/config/validators/NonEmptyPassword.java
- commons/src/main/java/io/aiven/kafka/tieredstorage/config/validators/Null.java
- commons/src/main/java/io/aiven/kafka/tieredstorage/config/validators/Subclass.java
- commons/src/main/java/io/aiven/kafka/tieredstorage/config/validators/ValidUrl.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/config/validators/NonEmptyPasswordTest.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/config/validators/NullTest.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/config/validators/SubclassTest.java
- commons/src/test/java/io/aiven/kafka/tieredstorage/config/validators/ValidUrlTest.java
- core/build.gradle
- core/src/main/java/io/aiven/kafka/tieredstorage/chunkmanager/ChunkManagerFactoryConfig.java
- storage/gcs/build.gradle
- storage/gcs/src/main/java/io/aiven/kafka/tieredstorage/storage/gcs/GcsStorageConfig.java
- storage/gcs/src/test/java/io/aiven/kafka/tieredstorage/storage/gcs/GcsStorageConfigTest.java
- storage/s3/build.gradle
- storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageConfig.java
* Moving common validators into single place e.g. additional module
* Adding a couple of new validators
* Validators usage cleanup
> Config validators refactoring

- storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageConfig.java
- storage/s3/src/test/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageConfigTest.java
Adding AWS API timeout configs
> AWS api timeout configs

- storage/s3/build.gradle
- storage/s3/src/integration-test/java/io/aiven/kafka/tieredstorage/storage/s3/S3ErrorMetricsTest.java
- storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/MetricCollector.java
Adding metrics for AWS S3 errors
> AWS error metrics

- core/src/main/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/DiskBasedChunkCache.java
- core/src/main/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/DiskBasedChunkCacheMetrics.java
- core/src/test/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/DiskBasedChunkCacheMetricsTest.java
This commit adds new metrics focused on disk cache write rate.
> Measure disk cache writes

- core/src/main/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/DiskBasedChunkCache.java
- core/src/main/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/DiskBasedChunkCacheMetrics.java
- core/src/test/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/DiskBasedChunkCacheMetricsTest.java
This commit adds new metrics focused on disk cache delete rate.
> Measure disk cache deletes

- demo/Makefile
- demo/compose-azure-blob-azurite.yml
- demo/compose-gcs-fake-gcs-server.yml
- demo/compose-local-fs.yml
- demo/compose-s3-aws.yml
- demo/compose-s3-minio.yml
1. Start using disk cache with prefetching.
2. Change to the standard 4 MiB chunk size.
3. Change demo topic sizes a little.
> Refresh demo

- demo/compose-azure-blob-azurite.yml
- demo/compose-gcs-fake-gcs-server.yml
- demo/compose-local-fs.yml
- demo/compose-s3-aws.yml
- demo/compose-s3-minio.yml
- e2e/src/test/java/io/aiven/kafka/tieredstorage/e2e/SingleBrokerTest.java
> Remove unnecessary prefix settings

- core/src/test/java/io/aiven/kafka/tieredstorage/chunkmanager/cache/ChunkCacheTest.java
- core/src/test/java/io/aiven/kafka/tieredstorage/manifest/SegmentManifestProviderTest.java
This commit adds tests that ensure the failed futures in our caches don't stay there after their failure is found out. The removal is handled by Caffeine.
> Explicitly test against cache poisoning with failed futures

- README.md
- core/src/integration-test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java
- core/src/main/java/io/aiven/kafka/tieredstorage/fetch/cache/DiskChunkCache.java
- core/src/main/java/io/aiven/kafka/tieredstorage/fetch/cache/DiskChunkCacheConfig.java
- core/src/main/java/io/aiven/kafka/tieredstorage/fetch/cache/DiskChunkCacheMetrics.java
- core/src/main/java/io/aiven/kafka/tieredstorage/fetch/cache/MemoryChunkCache.java
- core/src/test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerMetricsTest.java
- core/src/test/java/io/aiven/kafka/tieredstorage/fetch/ChunkManagerFactoryConfigTest.java
- core/src/test/java/io/aiven/kafka/tieredstorage/fetch/ChunkManagerFactoryTest.java
- core/src/test/java/io/aiven/kafka/tieredstorage/fetch/FetchChunkEnumerationSourceInputStreamClosingTest.java
- core/src/test/java/io/aiven/kafka/tieredstorage/fetch/cache/ChunkCacheMetricsTest.java
- core/src/test/java/io/aiven/kafka/tieredstorage/fetch/cache/ChunkCacheTest.java
- core/src/test/java/io/aiven/kafka/tieredstorage/fetch/cache/DiskChunkCacheConfigTest.java
- core/src/test/java/io/aiven/kafka/tieredstorage/fetch/cache/DiskChunkCacheMetricsTest.java
- core/src/test/java/io/aiven/kafka/tieredstorage/fetch/cache/DiskChunkCacheTest.java
- demo/compose-azure-blob-azurite.yml
- demo/compose-gcs-fake-gcs-server.yml
- demo/compose-local-fs.yml
- demo/compose-s3-aws.yml
- demo/compose-s3-minio.yml
- e2e/src/test/java/io/aiven/kafka/tieredstorage/e2e/SingleBrokerTest.java
> refactor: rename Chunk Cache 

- demo/compose-azure-blob-azurite.yml
- demo/compose-gcs-fake-gcs-server.yml
- demo/compose-local-fs.yml
- demo/compose-s3-aws.yml
- demo/compose-s3-minio.yml
- docker/Dockerfile
Update configs to latest changes and use latest Kafka
> chore: update to Docker demo

- core/src/main/java/io/aiven/kafka/tieredstorage/fetch/cache/DiskChunkCache.java
Move disk cache files movement logging to trace level.
> chore: reduce logging

- .github/workflows/codeql-analysis.yml
- .github/workflows/create_release.yml
- .github/workflows/main_push_and_pull_request_workflow.yml
- .github/workflows/release_pr_workflow.yml
Upgrading because of GH warning
> GitHub actions upgrade

- .github/workflows/codeql-analysis.yml
> GitHub CodeQL action upgrade

- storage/azure/src/main/java/io/aiven/kafka/tieredstorage/storage/azure/AzureBlobStorage.java
There's no reason in passing raw Reactor and other similar exceptions upstream.
> Wrap more Azure errors in StorageBackendException

- storage/gcs/src/main/java/io/aiven/kafka/tieredstorage/storage/gcs/GcsStorage.java
There's no reason in passing library internal exceptions upstream.
Also, this commit adds the handling of 404 during fetch.
> Wrap more GCS errors in StorageBackendException

- core/src/integration-test/java/io/aiven/kafka/tieredstorage/RemoteStorageManagerTest.java
- core/src/main/java/io/aiven/kafka/tieredstorage/config/CacheConfig.java
- core/src/main/java/io/aiven/kafka/tieredstorage/fetch/index/MemorySegmentIndexesCache.java
- core/src/test/java/io/aiven/kafka/tieredstorage/config/CacheConfigTest.java
Cleanup code accepting Optional types, see https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/pull/531#discussion_r1553816416
> refactor: Remove Optional input parameters

- storage/azure/build.gradle
- storage/gcs/build.gradle
> fix: dependency conflicts on storage back-ends

- Makefile
- build.gradle
> chore: fix minor build issues

- Makefile
- docs/build.gradle
- docs/configs.rst
- docs/metrics.rst
- docs/src/main/java/io/aiven/kafka/tieredstorage/misc/ConfigsDocs.java
- docs/src/main/java/io/aiven/kafka/tieredstorage/misc/MetricsDocs.java
- storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageConfig.java
> feat: add metrics document generation

- README.md
Also close some gaps on the docs.
> docs: update README with configs and metrics references

- storage/s3/src/integration-test/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageTest.java
- storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3Storage.java
AWS and other S3 implementtions limit the maximum number of keys to be deleted in a single request[1]
Adding a limit to batch deleteObjects requests.
[1]: https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html
> fix(storage:s3): limit delete keys to 1000

- .github/workflows/create_release.yml
File system has not been included in the releases. This PR fixes it.
Resolves: #570
> chore(ci): add filesystem module to release

- README.md
Include references to Kafka documentation for RLMM and remote fetching.
> docs: add references to kafka configs

- storage/core/src/main/java/io/aiven/kafka/tieredstorage/storage/proxy/Socks5ProxyAuthenticator.java
- storage/core/src/test/java/io/aiven/kafka/tieredstorage/storage/proxy/Socks5ProxyAuthenticatorTest.java
This operation is idempotent and should be allowed.
> Allow calling addCredentials with same credentials

- build.gradle
- docs/configs.rst
- storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3ClientBuilder.java
- storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageConfig.java
- storage/s3/src/test/java/io/aiven/kafka/tieredstorage/storage/s3/S3ClientBuilderTest.java
- storage/s3/src/test/java/io/aiven/kafka/tieredstorage/storage/s3/S3StorageConfigTest.java
> fix(s3): Add LegacyMd5Plugin to S3 client builder

- demo/iceberg/docker-compose.yml
> fix wrong mc usage for bucket init
